// Copyright 2025 NoSQLBooster All rights reserved. Generated by NoSQLBooster 10.0.5
import mongoose from 'mongoose';
const { Schema } = mongoose;

const cardSchema = new Schema({
    id: Number,
    title: String,
    featured_image: String,
    text: String,
    content: {
        paragraphs: [String],
        lines: [String],
        html: String
    },
    card_code: String,
    card_release: String,
    legion: {
        names: [String],
        slugs: [String]
    },
    set: {
        names: [String],
        slugs: [String]
    },
    variant: {
        names: [String],
        slugs: [String]
    },
    rarity: {
        names: [String],
        slugs: [String]
    },
    card_type: {
        names: [String],
        slugs: [String]
    },
    card_subtype: {
        names: [String],
        slugs: [String]
    },
    card_srl: {
        names: [String],
        slugs: [String]
    },
    keywords: {
        names: [String],
        slugs: [String]
    },
    permalink: String,
    attack: Number
}, { collection: "cards" });

export const Card = mongoose.model("Card", cardSchema);
