export enum CARD_TARGET {
  P1_PLAYER_HAND = "p1PlayerHand",
  P1_PLAYER_DECK = "p1PlayerDeck",
  P1_PLAYER_DISCARD = "p1PlayerDiscard",
  P1_PLAYER_ERADICATION = "p1PlayerEradication",
  P1_PLAYER_FORTIFIED = "p1PlayerFortifieds",
  P1_PLAYER_UNIFIED = "p1PlayerUnifieds",
  P1_PLAYER_WARRIOR = "p1PlayerWarriors",
  P1_PLAYER_GUARDIAN = "p1PlayerGuardian",
  P1_PLAYER_SYNERGY = "p1PlayerSynergy",
  P1_PLAYER_VEIL_REALM = "p1PlayerVeilRealm",
  P1_PLAYER_WARLORD = "p1PlayerWarlord",
  P1_PLAYER_TOKENS = "p1PlayerTokens",
  P1_PLAYER_REVEALED = "p1PlayerRevealed",
  // P1_PLAYER_BLANK = "p1PlayerBlank",
  
  // P2_PLAYER_BLANK = "p2PlayerBlank",
  P2_PLAYER_HAND = "p2PlayerHand",
  P2_PLAYER_DECK = "p2PlayerDeck",
  P2_PLAYER_DISCARD = "p2PlayerDiscard",
  P2_PLAYER_ERADICATION = "p2PlayerEradication",
  P2_PLAYER_FORTIFIED = "p2PlayerFortifieds",
  P2_PLAYER_UNIFIED = "p2PlayerUnifieds",
  P2_PLAYER_WARRIOR = "p2PlayerWarriors",
  P2_PLAYER_GUARDIAN = "p2PlayerGuardian",
  P2_PLAYER_SYNERGY = "p2PlayerSynergy",
  P2_PLAYER_VEIL_REALM = "p2PlayerVeilRealm",
  P2_PLAYER_WARLORD = "p2PlayerWarlord",
  P2_PLAYER_TOKENS = "p2PlayerTokens",
  P2_PLAYER_REVEALED = "p2PlayerRevealed",

  CONTROLLER_DECK = "controllerDeck",
  CONTROLLER_HAND = "controllerHand",
  CONTROLLER_DISCARD = "controllerDiscard",
  CONTROLLER_ERADICATION = "controllerEradication",
  CONTROLLER_FORTIFIED = "controllerFortified",
  CONTROLLER_UNIFIED = "controllerUnified",
  CONTROLLER_WARRIOR = "controllerWarrior",
  CONTROLLER_REVEALED = "controllerRevealed",
}